### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Mattia98** [xn--nding-jua/Ampdroid#1]
Everytime I try to log in it says Connection Refused.

**Comment by xn--nding-jua** [comment]
Hi. What vesion of ownCloud and the Music-App did you use?

1. Make shure, that in the personal settings of ownCloud an API-password is set.
2. enter the following link as server in Ampdroid: https://www.abc.xyz/index.php/apps/music/ampache
3. Enter your ownCloud-username and the password to this user
4. enter the API-password
5. click "save" and maybe "Reset cache"

Then it should work.

**Comment by Mattia98** [comment]
Hm.. I've probably misspelled my password because it works now.. Maybe adding a "wrong Username or Password" message would improve UX

**Comment by xn--nding-jua** [comment]
Yes, you are right. I will see what I can do, when I'm sitting on the code next time.
